POST http://localhost:8800/hotels

{
    "name": "Hotel Jane",
    "type": "hotel",
    "city": "berlin",
    "address": "somewhere",
    "distance": "500",
    "title": "Best Hotel in town",
    "desc": "description",
    "cheapestPrice": 100
}

###

GET http://localhost:8800/hotels

###

GET http://localhost:8800/hotels/countByCity?cities=berlin,london,madrid